name: Build

on: [push]

jobs:
  code_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Use Cache
        uses: actions/cache@v2
        id: app_cache
        with:
          path: ~/go/pkg/mod
          key: ${{ env.cache-version }}-${{ runner.OS }}-${{ hashFiles('**/go.sum') }}

      - name: Install dependencies
        if: steps.app_cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Execute code check
        run: go vet ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Use Cache
        uses: actions/cache@v2
        id: app_cache
        with:
          path: ~/go/pkg/mod
          key: ${{ env.cache-version }}-${{ runner.OS }}-${{ hashFiles('**/go.sum') }}

      - name: Install dependencies
        if: steps.app_cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Execute code check
        run: go test ./...
