name: "Schedule event"

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Use Cache
        uses: actions/cache@v3
        id: app_cache
        with:
          path: ~/go/pkg/mod
          key: ${{ env.cache-version }}-${{ runner.OS }}-${{ hashFiles('**/go.sum') }}

      - name: Install dependencies
        if: steps.app_cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Execute
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER_NAME: ${{ github.repository_owner }}
          GITLAB_USER_ID: ${{ secrets.GITLAB_USER_ID }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_COMSUMER_KEY: ${{ secrets.TWITTER_COMSUMER_KEY }}
          TWITTER_COMSUMER_SECRET: ${{ secrets.TWITTER_COMSUMER_SECRET }}
        run: go run src/cmd/main.go
